### ISSUE TITLE
Update Documentation for Accuracy

### ISSUE THREAD

**Issue by Armeanio** [rosen-bridge/Catalyst-Fund10#1]
The collateral required to run a Watcher is around (due to market volatility) $1,000 in RSN tokens and $1,000 in Ergo. This substantial cost acts as a deterrent, limiting the number of Watchers any single entity can operate, thus preventing sybil attacks.

Remove the Following **This initial collateral is not subject to seizure however does come with impermanent loss risks.**

Replace with 

The initial collateral is not subject to seizure, it is locked should be considered illiquid by Watchers until redemption occurs.

**Comment by mhssamadani** [comment]
updated.
